server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  location = /knowledge {
    return 308 /knowledge/;
  }

  location /knowledge/ {
    try_files $uri $uri.html $uri/ /knowledge/index.html;
  }

  location / {
    return 404;
  }
}
