// Generated by scripts/encrypt-puzzle-answers.mjs. Plaintext answers are intentionally not committed.

export interface EncryptedPuzzleAnswer {
  iterations: number
  salt: string
  iv: string
  ciphertext: string
}

export const encryptedProjectEulerAnswers: Record<string, Record<'en' | 'zh', EncryptedPuzzleAnswer>> = {
  "1": {
    "en": {
      "iterations": 210000,
      "salt": "YuQGgN2kpq98waJqe0aKnA==",
      "iv": "7f1z6BXguWDxx1dK",
      "ciphertext": "LHYcEDB1fk/hhbbfUAzLTDL3V0HSMptCdTnmbPyl7wyH2vJYuX3CDn58l8rswptinIUSWMECl8inEG8m5o1EqfOk+ATxQmxe2oqyrkTg3/pW5pOlo0qviJwtYW7kyAeCRrm6Kqj+fO+unlY3hzCivupEYYhm2BI581tpXfD91AhKCkn7glAjJ7JrbHFHNfxgn9Y2yR4fJktm65RtzIdhQRBL8vKo2hO60CTat41GCO1z3RdbfMw5b36LFwbtd105FMf9O5ksD14108B1U+RVt2GHmA0X6EWWD3B/qXIyerJ6pb2SszlQ/8v4JEIIchUI7TXEoWVzgjIwvb1JC7B8ruJsm/8huC3n9P5ubUV5QulJhnitInSCAOxdwyFpZ9k2VKd2CVjGi+ExfBdOWAmf/1TZfsRUGoqm/DIDX/2vb+JdEaQlpw2uSe4Wp76rBWy/+pmZWUf0XepguIOo+LWFtqKO9rhRxoF3yM3f9KGqr4eUHozZFo8m0UJwqfdAmL21v6sJCZGzRgBoE2ixSoxH65MnWFKFWGnsMndekxJm0hOb9ECzm0+57HiKJwETpYFwobYGo5goFHhw99Njf29dzi+rSm9i4zb8pk18I7vww01FN8k="
    },
    "zh": {
      "iterations": 210000,
      "salt": "ntTK8lNb6fweHCte4Pj5Gw==",
      "iv": "IwfRLrvnpH8FycyO",
      "ciphertext": "v31ZIPGGpJZLa3E3LZl7d/8rDb/0uBtwcYmZu32F/o3L8qtaWJPuR5Ehhqn/4uWGNGukeop0NSeWglsPDBKkL56/89YJp0u+lXdovXtl8EMR6fZLqtur6+mUZr5++Ie0O5CORHGA9SpgLR6uRdop5YIGfPIOS6P/HevFUxBYENNaV7aS0gyLoz5syjJZZAHJvuw2lB91qisP7/SjdjNxakfvDuqw2Fl7bdQuOJjH3W2SRuQCn7eHZdtjuMz+yfDPEMvrYlettzs56dPsSPSetMhFWvni7ISOtg6jTF3p0ycI2bE6KQRrb5bezjj3pp/ChXXLbxV08igRdztpoTzKkOl7R+rGOoo5Q6HQHStPqsKOn4QoLP5yRg7ETwUBnY2T7ty4C5EZxoz9rhWDl3h0Zn7mZut0//xDDfQKkNj0+7ot3LlYXJFhdDdbDLtLtU/GN9ekSHR1V8MhYa/+D5ATr2HctgZ65rIGr0nRdAvps6jt/Qxbp2yDQm1W9rN7QSX1ris6DcQAMZvMAO6AQVRkWqg/07EDJDCU1GXFKHZ7+6aaUoaEe/AU4itiLANVLsxdi2XhDwr4DVDkCO5tjriZIxf5jI9E7OQwge5Tt+LjVrf4xTk="
    }
  },
  "2": {
    "en": {
      "iterations": 210000,
      "salt": "WbGI1WvI2jd5Rt823HUbBg==",
      "iv": "3rhTba3vBeThgyvT",
      "ciphertext": "qGyYlizidy9P6JXLzg1OGsuX7w1vlckVZ4PdofnCL4ZhICLHGuv7dcfYsuyF1ivuyYBwHSJ1iNKfgaFmSrdavZSYwoz6bslfwrbumYQHT4vIgMkp7L1kCKNPoMEB4Angoa+85PO4wv5uI9ECQV1YPEnb/Lg+w5ZojmkOx39mOmnHxEobokZAwItvb8RNr2NkAsRCAhTg124YbcZr38e1Pyh4bFCOrp3TuX69dOEggRSceFxlNiF/tFkeJgv3g7CvzpBUtab+4+M27dE49RpTZ6D07MCjFckfsf6jMkNbGs4QguY1YNRcnbTxi7E7JVigMC7KM38BJtaqk1/SmIbGN7AgXwvPU8peJKVnT63bJDSlj3G7lINfvScb4goChaP3wLvDZrvybDk9aH9Jm/kPLdy2XbDYklzFQqyZsUz9kM6iKp3VnCjzFAqR9AvEV5HyxYDGdzvm7DLqVyJMHCXKKUiFlInVkjcDdrE3jGMGG65DIFZmupeWThw8IsBKyKzqSCM8/cJCd75hIuu4G4ZoGxa1TIL6HHwBH5aN03nCSH9syM0clH43jD/CSuA1WJbXbDHVoxD8QUo+ojqTBdTVaPcBJXqZ/RzWTMbzq0JlfbyILD0xe9YUaVrL+s8MAlMsgWhlykAJinIT+/I="
    },
    "zh": {
      "iterations": 210000,
      "salt": "qDkCHSSwtjn+kz+MRNLamg==",
      "iv": "tQyDXK4jHSP+o1wc",
      "ciphertext": "DzMLp723xwdXgQuC4bns+ytpMneJ3wKbw2bixrbaLG4nVKwa3D75mRuDssnpyjtXir/CwQw8cFd6ttnCPARuNI/cDAOQp6nx8XijivkGKa/zcxc0hyLW7Cup07bCi9ONVENKlbDhCu2sB4+ZvhHuZGsbRbd/rAhpGmJZSzjoWD583pPs+u1Zd7QU5rIn4kTRRXkIAjdbNQ5SlAqVkj3zgDT93m3cNZyCHQm7hq3U3vhUsao/hlIOVJhhdax7J+9amLp5oIHLuzQWre/2FQsZDvSQYhQGsrWAh6voSQT84RnN8WvqmO68O7s/uTk/wo0z978TlWmw47aFCBcFEo2DNKyp4owjEBtYr0oXmi2tUJQpH9GVvDcBqTiAGT3OiI8iryO6bRFaew2iJ5N2D4ke6p9zBgGIJCz3iwS+HvI5RZoa7f9NSjV3RBAPBBvA28Tcc9cF6GsW200wmmbAx6pX3+kllgf+H4AyCaSd1LQ9AhNYiwlnwIhhMAJT1QccsJyTh57qOzVjkOixU4AWOhp1oNiF95O2yKSviCi2kZHXH2F1r9gaUi6MiIA4asMKHrxjFW+NrJJ+w1CgBBteHngxQe0f1YMr06NPH9qml/QjDDII1IV9MX/esrsVOYv8ZjE0dDWNy1Gs0xH0wW4="
    }
  },
  "3": {
    "en": {
      "iterations": 210000,
      "salt": "ql0xYMETIxm8OvaTSfNYzA==",
      "iv": "MtmnWNP28G8apKA7",
      "ciphertext": "u8NrBvTazIIizzvH64PdDDH5sMENgMhPdMEypJ89qpXhbLNE7Gkp/LBgeTGpqYL/CHLT8Njl7L1LHycwO8iMKv8HDnyOszrwuVoHzDQIHjoTsVskjpTpeTxmQ8l+a83zMPfrhMFBK4dA8Xt4SlOEnP5muaFnG+XBX/P82NhHHDbXV4ePVFdnlr/UlR+uniBCP1vSRpjoOYgqVr68tBTgO98S+e5dxlLIuiZrjqG3DqYqg4/jnFJN/de5xZ83W2H29q2camHP/Zl0wUN+glk8lt+iVpP21kKHsEmBj55oTYer4i5S/wLRjVDCs5vfru5ZpmYH4bHDDPE5k/i1ORyScGEJMPMCEjVCmQwGBNCowSodW5igBjqRdnfRcYc+N/bbQcbVBsognVaEb58IuDGWf+FeWnTYAB/5oNqD+TD0z8H0TNzUmF0KcSuaRs8VhGQpOB7a9gE2n8py57ibo+0W+y4JpB84ahK9rtUVK4iIrEo1Bsy1BHzdAa7PD3Pt7iaROMiUGFASU4OyS/1SX4y+U/GfipHdzxVLzkj1HG6VwPr619AOQVt9/eZneCZD26KhtQjznVrdRQ/hC4cJQ22HtaoRfwN+w5hc7ZkxaUCi/BAEbivdzwLodT86yfPy10QkUwGXVcRnqEj6hIMktGCAb9Q4VqtdlV/G3vt1l7JONd4Dro3TosTi8kPCO1+qtk/b73V0n45KQlSAC5kW85HGfun8rwjRUw=="
    },
    "zh": {
      "iterations": 210000,
      "salt": "W6zHF2rEgByKLlDW55+HNw==",
      "iv": "ybBsXU9BCvRWlr9m",
      "ciphertext": "rGAeNQ6Bx+b3784vpRygaIZnA+u+CoF1GyWOmugF5y39ZeDOO9EOJ8OL+egd6nlYT86HEAeH8u189IW7t8L4pcpBpz8bZHL45Y6JozFF31dbHFvLxmY88tPf51dY1bvIjUxfEovTz5597MjNWEwj/zUgwLpufo3kZMhp3vOaV0mHjj0W3kXuG9ge2IPENhW8HjkwElyWt0GNAh3CXt2JiY9QRJwUlrE+wcFBmaKXs9u8pN2MiLTBrO1DOYHa4G+v4kEnlWtzDcUsZmMy98SJ1/9qkMCTMvadmQ8t9zrN8iWJz/Fs9SZ65hR0D9fokHX1dz9oqKqKYCZ8EzGv8stm8KAi1vd4RYCFZMGh1Aa5J3ZI8yvitLec/bucGEwk3orA7c3DoYWVkuxjJTEdwSuiEIJ0oYKP+1PcCPNaod4BbDR5CPu+0NTZPU9LT+RwGqImaRdtiLoRDWD1Ur0XklpLF/F2szZ/zpMSHW55njJejYQKmQ7IQy0ISf4didrJd8Ttlk4UjmdsEOv/08RV1Sujiff2ri2Htekba0EvHxMfOoN/QfLuG8DJCquUAHiqjzVwdle6kY8X6wUXTfXgvLQe0F31z2VMCCMMIx+DVs72z8mzJy1Wpkj0wl451iX2sfi3qVqhSSSvHdm8IaMBZFzmXdbksBwe/cnq8k1VQ1FUxhLz1B5btYXkGCt1D3CTrs1PW03N6ERALTLIxO02IeDfrD4ARGaqYA=="
    }
  }
}
